# Generated by Django 5.0.1 on 2024-01-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutingInOutTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outTime', models.DateTimeField(auto_now_add=True)),
                ('inTime', models.DateTimeField(blank=True, null=True)),
                ('remark_by_security', models.TextField(null=True)),
                ('outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.outing')),
            ],
            options={
                'ordering': ['-outTime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('security_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('Superintendent', 'Superintendent'), ('Chief', 'Chief')], max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
